# Generated by Django 3.1.1 on 2020-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
