# Generated by Django 3.1.1 on 2020-09-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200926_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='head_of_the_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
